### ISSUE TITLE
port kubetop to Python 3

### ISSUE THREAD

**Issue by jason-kane** [LeastAuthority/kubetop#30]
`pip3 install kubetop` on 16.04 ubuntu leads to:

```
$ kubetop 
Traceback (most recent call last):
  File "/usr/local/bin/kubetop", line 7, in <module>
    from kubetop._script import main
  File "/usr/local/lib/python3.5/dist-packages/kubetop/_script.py", line 27, in <module>
    from ._textrenderer import Sink, kubetop
  File "/usr/local/lib/python3.5/dist-packages/kubetop/_textrenderer.py", line 114
    def _render_pod_top(reactor, (node_info, pod_info)):
                                 ^
SyntaxError: invalid syntax
```

**Comment by jason-kane** [comment]
ala PEP 3113
https://www.python.org/dev/peps/pep-3113/ 
http://twistedmatrix.com/trac/ticket/8346?cversion=1&cnum_hist=11

**Comment by exarkun** [comment]
Indeed.  kubetop is currently Python 2-only.  `pip install kubetop` (per the instructions in the README) will succeed.

Presumably there are more issues than just this syntax error preventing it from running on Python 3.  For example, the txkube dependency is also Python 2-only.  So porting that to Python 3 would be a first step to addressing this.

**Comment by gjcarneiro** [comment]
IMHO a new tool like kubetop should be Python 3 only from the start.  Why bother with Python 2 in 2017?...

**Comment by exarkun** [comment]
> IMHO a new tool like kubetop should be Python 3 only from the start. Why bother with Python 2 in 2017?...

I eagerly await your PR.

**Comment by rodrigc** [comment]
@jason-kane see these pull requests:

- https://github.com/LeastAuthority/kubetop/pull/50
- https://github.com/LeastAuthority/kubetop/pull/51
- https://github.com/LeastAuthority/kubetop/pull/52
- https://github.com/LeastAuthority/kubetop/pull/53
- https://github.com/LeastAuthority/kubetop/pull/54
- https://github.com/LeastAuthority/kubetop/pull/60

**Comment by jason-kane** [comment]
I opened the ticket but am not a kubetop developer so couldn't merge even if I knew the codebase well enough to adequately review.  I think you want @exarkun.

**Comment by rodrigc** [comment]
I just wanted to let you know that things are in progress.  exarkun will of course be doing the reviews and any merges.
