### ISSUE TITLE
Distribute as a docker container?

### ISSUE THREAD

**Issue by rothgar** [LeastAuthority/kubetop#36]
I think this could be great to distribute as a docker container.

Run with
```
docker run -it -v $HOME/.kube:/root/.kube kubetop
```

I was going to push my own container, but couldn't figure out the exact requirements to make it run.

**Comment by exarkun** [comment]
Seems reasonable.  I think I can probably put together a Dockerfile pretty quickly, too...

**Comment by rothgar** [comment]
You could also make it auto discover the kubernetes dns entry point and use pod certificates if they exist. Then you could just as easily run the container on the kubernetes cluster itself and attach the terminal back.

e.g.
```
kubectl run -it kubetop --image LeastAuthority/kubetop --restart=Never
```
There's no reason to run it locally :wink:

**Comment by exarkun** [comment]
Heh.  Indeed. :)  I think I'll save that feature for later though.
