### ISSUE TITLE
Add 'topics' to the project to make it more discoverable

### ISSUE THREAD

**Issue by tyrannasaurusbanks** [LeastAuthority/kubetop#42]
@exarkun I don't know if you've seen it, but you should have the option to add some topics to the project - you could tag it with 'kube', 'monitoring', 'top', etc to help make it more index-able by github. 
Kube-AWS project page for example:
![screen shot 2017-05-18 at 9 20 26 am](https://cloud.githubusercontent.com/assets/2912093/26192992/a6405a76-3bab-11e7-8abd-8a239f91fe97.png)

**Comment by exarkun** [comment]
Great idea, thanks.  I've added some topics.
