### ISSUE TITLE
Exceptions running both docker and local version

### ISSUE THREAD

**Issue by mikhail-manuilov** [LeastAuthority/kubetop#48]
$ docker run -it --rm --volume ~/.kube/:/root/.kube/:ro exarkun/kubetop
Unable to find image 'exarkun/kubetop:latest' locally
latest: Pulling from exarkun/kubetop
79650cf9cc01: Pull complete 
581a2604819e: Pull complete 
a7826377ee0a: Pull complete 
406f1af34710: Pull complete 
6322e2dfca88: Pull complete 
f4278c7f5467: Pull complete 
43da5e7d9205: Pull complete 
94e609f3078b: Pull complete 
Digest: sha256:fc6a1f382cb6775862a109b02760a40a6117f0ea9f8cd43e9f143e9e990c37d7
Status: Downloaded newer image for exarkun/kubetop:latest
Traceback (most recent call last):
Failure: twisted.internet.defer.FirstError: FirstError[#1, [Failure instance: Traceback (failure with no frames): <class 'twisted.internet.defer.FirstError'>: FirstError[#1, [Failure instance: Traceback: <type 'exceptions.AttributeError'>: 'schedulerName' are not among the specified fields for v1.PodSpec
/usr/local/lib/python2.7/site-packages/twisted/web/_newclient.py:1185:_bodyDataFinished_CONNECTED
/usr/local/lib/python2.7/site-packages/twisted/web/client.py:2115:connectionLost
/usr/local/lib/python2.7/site-packages/twisted/internet/defer.py:457:callback
/usr/local/lib/python2.7/site-packages/twisted/internet/defer.py:565:_startRunCallbacks
--- <exception caught here> ---
/usr/local/lib/python2.7/site-packages/twisted/internet/defer.py:651:_runCallbacks
/usr/local/lib/python2.7/site-packages/eliot/twisted.py:82:callbackWithContext
/usr/local/lib/python2.7/site-packages/eliot/_action.py:389:run
/usr/local/lib/python2.7/site-packages/txkube/_network.py:271:<lambda>
/usr/local/lib/python2.7/site-packages/pyrsistent/_helpers.py:80:inner_f
/usr/local/lib/python2.7/site-packages/txkube/_model.py:379:iobject_from_raw
/usr/local/lib/python2.7/site-packages/pyrsistent/_pclass.py:113:create
/usr/local/lib/python2.7/site-packages/txkube/_model.py:256:__new__
/usr/local/lib/python2.7/site-packages/pyrsistent/_pclass.py:52:__new__
/usr/local/lib/python2.7/site-packages/pyrsistent/_checked_types.py:200:_checked_type_create
/usr/local/lib/python2.7/site-packages/pyrsistent/_pclass.py:113:create
/usr/local/lib/python2.7/site-packages/pyrsistent/_pclass.py:52:__new__
/usr/local/lib/python2.7/site-packages/txkube/_swagger.py:255:optional
/usr/local/lib/python2.7/site-packages/pyrsistent/_pclass.py:113:create
/usr/local/lib/python2.7/site-packages/pyrsistent/_pclass.py:67:__new__

**Comment by exarkun** [comment]
Thanks for your interest in txkube.  This is the same as issue https://github.com/LeastAuthority/kubetop/issues/33
