### ISSUE TITLE
python setup.py develop fails on Python 3

### ISSUE THREAD

**Issue by rodrigc** [LeastAuthority/kubetop#56]
I tried to run `python setup.py develop` on Python 3 and got this:

```
Traceback (most recent call last):
  File "setup.py", line 8, in <module>
    exec(f.read(), _metadata)
  File "<string>", line 3, in <module>
TypeError: unsupported operand type(s) for +: 'map' and 'list'
```

**Comment by exarkun** [comment]
Hm.  I'm not sure I'm interested in `setup.py develop`.  I think it is setuptools historical cruft.  I think everyone should be using `pip install -e .[dev]` now.
